import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Cookies from 'js-cookie'

const getDeliciousCookie = () => Cookies.get('delicious')

const SITE_B = 'https://siteb.pango.plus'
const ENDPOINT = `${SITE_B}/api/cookie`

export default function Home() {
  const [isFetched, setIsFetched] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [cookie] = useState(getDeliciousCookie)

  const fetchToGetCookie = async () => {
    setIsLoading(true)
    try {
      await fetch(ENDPOINT, {
        mode: 'cors', 
        credentials: 'include'
      })
      setIsFetched(true)
      setIsLoading(false)
      setTimeout(() => {
        window.location = SITE_B
      }, 10)
    } catch(error) {
      console.log(error)
    }
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Cross Domain POC - Site A</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Cross Domain Cookie - Site A</h1>
        <ul>
          <li>
            <button className={styles.button} onClick={fetchToGetCookie} disabled={isLoading}>go to siteB</button>
          </li>
          <li>
            cookie value: {cookie}
          </li>
          <li>
            hint: {isFetched ? 'fetched!' : isLoading ? 'fetching' : 'please click button' }
          </li>
        </ul>
      </main>
    </div>
  )
}
