import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const SITE_B = 'siteb.pango.plus'


export default function Home() {
  const [isFetched, setIsFetched] = useState(false)
  const [isLoading, setIsLoading] = useState(false)

  const fetchToGetCookie = async () => {
    setIsLoading(true)
    await fetch(SITE_B, { mode: 'cors', credentials: 'include' })
    setIsFetched(true)
    setIsLoading(false)
  }

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script>
        </script>
      </Head>

      <main className={styles.main}>
        <h1>Cross Domain Cookie - Site A</h1>
        <ol>
          <li>
            <a href={SITE_B}>Go to Site B -- {SITE_B} to get cookie at first</a>
          </li>
          <li>
            <button className={styles.button} onClick={fetchToGetCookie} disabled={isLoading}>click to fetch Cookie</button>
          </li>
          <li>
            hint: {isFetched ? 'fetched!' : isLoading ? 'fetching' : 'please click button' }
          </li>
        </ol>
      </main>
    </div>
  )
}
